### ISSUE TITLE
download script install perl modules that are already installed

### ISSUE THREAD

**Issue by lemmy04** [themoriarti/xt_asn#3]
why is the downloader script installing perl modules that are already on the system, but then fails because of another **missing** perl module?

**Comment by themoriarti** [comment]
What is the operating system and version?
Which Perl packets caused the problem?

**Comment by lemmy04** [comment]
opensuse leap 15.0, and the build script needs Text::CSV_XS which is not installed by default... but available.
I'm trying to package xt_asn as a rpm package so I can just drop in the requirement, **but**: the downloading and installing of two perl modules from source is a no go.

**Comment by lemmy04** [comment]
it's in xt_asn_dl.

**Comment by lemmy04** [comment]
also: xt_asn_dl expects bgpdump in /usr/local/bin instead of anywhere in $PATH.

**Comment by hgshoggins** [comment]
I had to create a symlink between `/usr/bin/bgpdump` and `/usr/local/bin` to make it work.
